// Service worker content removed as offline functionality is disabled.
// This file might still be generated by the build process but will be empty or minimal.
console.log('Service worker script loaded, but functionality is disabled.');
